name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        flutter_channel: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install CMake and Ninja
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y cmake ninja-build
      
      - name: Install GTK and pkg-config (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libgtk-3-dev pkg-config
        
      - name: Install Unwind (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libunwind-dev

      - name: Install GStreamer (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        if: matrix.os == 'ubuntu-latest'
        run: flutter build web

      - name: Upload Web Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web

      - name: Build Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk        

      - name: Upload Android Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/x64/runner/Release

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build/linux/x64/release/bundle